### ISSUE TITLE
Can't download image from restored mongodb database

### ISSUE THREAD

**Issue by ars096** [crowi/crowi#119]
I'm using crowi 1.4.0 on docker (provided as bakudankun/crowi:1.4.0).
I did following, then I can't download images.

1. Set-up new crowi server (crowi1) with envitonment FILE_UPLOAD=local
2. Create a user (user1)
3. Create a page (page1) and edit
4. Upload a image file (image1) on page1
5. Make backup using mongodump (Backup-A)
6. Set-up new crowi server (crowi2) with envitonment FILE_UPLOAD=local
7. Restore Backup-A into crowi2
8. I can login as user1
9. I can find page1 and its text
10. I can't find image1. There is a link of image1, but when I click it, crowi2 shows "Create: /uploads/attachment/..../....png" page.

crowi1 のデータベースを mongodump でバックアップし、crowi2 に mongorestore でリストアすると、ログインできて、作っていたページも確認できましたが、アップロードしていた画像ファイルはリンク切れになっていました。crowi1 の db を dropDatabase() するとログインできなくなりますが、crowi1 にリストアすれば、画像も含めて問題なく表示されました。

**Comment by smallfield** [comment]
On `FILE_UPLOAD=local` environment, uploaded images are not stored in MongoDB, but stored under `$CROWI_HOME/public/uploads` .
If you need to migrate or backup data, you need to backup both MongoDB and `$CROWI_HOME/public/uploads`.

`FILE_UPLOAD=local` の環境では、アップロードした画像は、`$CROWI_HOME/public/uploads` 配下に保存されます。
データのマイグレーションやバックアップを行う場合には、MongoDBのデータと上記ディレクトリを移行/バックアップする必要があるようです。

**Comment by Bakudankun** [comment]
これはCrowi本体ではなく[bakudankun/crowi](https://github.com/Bakudankun/docker-crowi)の問題です。

bakudankun/crowiではアップロードファイルの永続化のために`/usr/src/app/public/uploads`を`/data/uploads`へのシンボリックリンクとし、`/data`がVOLUMEとして登録されています（[参考](https://github.com/Bakudankun/docker-crowi#ボリューム)）。
ボリューム名を指定したりホストのディレクトリをマウントしたりすることで別のコンテナに引き継ぐことができます。

済みません、READMEの実行例は必要最低限を意識して書いていたので不親切だったかもしれません。
これを指摘するPR（ Bakudankun/docker-crowi#2 ）も戴いているので、1.5.0リリースの時に修正しようと思っています。

**Comment by ars096** [comment]
Thank you for your quick reply.
I can do it by backup /data/uploads directory.
早速のコメントありがとうございます。無事、データ移行できることを確認できました。
bakudankun/crowi:1.4.0 の README を確認不足でした。
