### ISSUE TITLE
Error on searching

### ISSUE THREAD

**Issue by Bakudankun** [crowi/crowi#120]
* Herokuにデプロイしていたv1.4.0からv1.5.0にアップグレード（単純にv1.5.0をpushしただけ）しましたが、検索フォームが表示されませんでした。
* おそらくアップグレードではbonsaiが入らないからだと思ってbonsaiを追加したところ、検索フォームは表示されるようになりましたが、何か検索しようとすると「Error on searching.」と表示されて検索することができません。検索結果ページに飛んでも「No page found」すら表示されません。適当な記事を作成したり編集したりしてみても変わりませんでした。
* Deploy to Herokuボタンから新規でアプリを作成（すべて無料プラン）しても、上と同じように「Error on searching.」が表示されます。

Deployあるいはbonsaiを追加した後で何か作業が必要なのでしょうか？

**Comment by kunitake** [comment]
私もここにつまづきましたが、リリースノートにあるように、"管理" -> "検索管理" -> "Build Now" で、検索する前に、インデックスを作成しておく必要があるようです。Elasticsearchでしか試してませんが、おそらく bonsai でも同じではないでしょうか

https://medium.com/crowi-book/crowi-v1-5-0-5a62e7c6be90#.r5nh2dxvm

**Comment by sotarok** [comment]
ですです
最初に、インデックス(正確にはマッピング)を作成する必要があります

> "管理" -> "検索管理" -> "Build Now"

**Comment by Bakudankun** [comment]
あ、気づきませんでした！
ありがとうございます！

**Comment by tttakaoka** [comment]
- v1.6.3 をherokuへdeploy
- bonsai add on しているが、error on searching となってしまう。
- 上記の `管理 > 検索管理 > Build Now` は実行済

以下に参考までにスクショつけておきます。ご確認お願いいたします 🙇 

<img width="646" alt="screen shot 2017-12-13 at 17 56 55" src="https://user-images.githubusercontent.com/10250656/33930220-8638ee72-e02f-11e7-8afd-49b02d314961.png">

![screen shot 2017-12-13 at 17 48 57](https://user-images.githubusercontent.com/10250656/33930211-8013107c-e02f-11e7-86b5-e6f791a1e653.png)
![screen shot 2017-12-13 at 17 49 30](https://user-images.githubusercontent.com/10250656/33930215-81f59b62-e02f-11e7-812b-183a396d829c.png)
