### ISSUE TITLE
Can't remove redirections

### ISSUE THREAD

**Issue by Bakudankun** [crowi/crowi#121]
リダイレクトを解除する機能が無いため種々の問題があります。
- 一度リダイレクトさせたページは再作成できない
- `/hoge`がどこかにリダイレクトされているとポータル`/hoge/`がポータル解除できない
  - そのため`/hoge/`は移動も削除もできない

リダイレクトを解除する機能か、あるいはリダイレクト機構自体を無くすか……が必要だと思います。

**Comment by sotarok** [comment]
おぉー、たしかにそのとおりですね。
(ちなみにそもそもでいうと、/hoge/ に portal が存在したら /hoge は自動でリダイレクトされるので、ページ移動で portal 化するときはリダイレクトページの作成へのチェックは不要です)

移動先がリダイレクト用のページがであれば作成できるように、というのは検討します。

**Comment by kkajita** [comment]
最初、仕様を理解できていなかったので、警告を無視して、/hogeをページ、/hoge/をポータルの状態にしてしまいました。
こうなると、/hogeを削除しても/trash/hogeへのリダイレクトが残り、/hogeから/hoge/へ自動リダイレクトされる状態にできません。
削除した時だけでもリダイレクトを解除できないものでしょうか。

**Comment by sotarok** [comment]
Implemented in #214
