### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by bravewood** [crowi/crowi#127]
I think that it will be great if there are some notifications triggered by user actions.

For instance:
- User creates/edits article
- User writes comment
- User likes article

I sometimes missed important comments or modifications on my article or other articles which I `Liked`.
I wanted to let me know when someone writes comment or edits article so that I respond to it as soon as possible.
For the sake of personal preference, it will be good that notifications can be turned on/off privately.

**Comment by sotarok** [comment]
It is planed to implement in near future.
I'm going to implement these feature list in order of priority.

**Comment by sotarok** [comment]
Will be implemented in v1.8
- https://github.com/crowi/crowi/pull/367
- https://github.com/crowi/crowi/pull/343
