### ISSUE TITLE
crowi.min.js is broken

### ISSUE THREAD

**Issue by Bakudankun** [crowi/crowi#135]
cf. Bakudankun/docker-crowi#3

crowi.min.jsが壊れるようになりました。
Dockerの[bakudankun/crowi](https://hub.docker.com/r/bakudankun/crowi/)（Node v4.6.1ですが）で確認した限りでは、10/25のビルドでは正しく動作し、11/1のビルドでは動作しません。

これはただの勘ですが、10/26にwebpackの1.13.3がリリースされたのが怪しいです……。

Crowi v1.5.0 on Heroku (node 4.2.6 / npm 3.3.12)

**Comment by sotarok** [comment]
おお、、
調べます
