### ISSUE TITLE
wikiの閲覧だけログインなしでできるようにしたい

### ISSUE THREAD

**Issue by subdiox** [crowi/crowi#155]
## 提案
crowiが社内用wikiを想定して作られているというのは承知しておりますが、crowiのデザインや機能性が好きなので、できれば閲覧だけはログインなしでできるようなオプションを設定画面に追加していただけないでしょうか。
よろしくお願いいたします。

**Comment by sotarok** [comment]
ご要望ありがとうございます。

ちょくちょく聞く要望ではあるので、どこかのタイミングで出来たら良いなーとは思ってはいます。。。！
ただ今はユーザーが居る前提の設計が多いので、色々考慮することがあるなーと。
例えば社外へ共有するみたいなときのための共有用リンク発行機能、みたいなものは考えています！

**Comment by sotarok** [comment]
直近のロードマップ上では優先度は高くはないと思っているので、気長におまちいただけると...!

**Comment by naoya** [comment]
+1

**Comment by sotarok** [comment]
( ﾟдﾟ)ﾊｯ!

**Comment by kubor** [comment]
+1

**Comment by yamasakih** [comment]
+1

**Comment by masaya-nakamura** [comment]
+1

**Comment by sotarok** [comment]
We do not have plan to make whole pages on wiki accessible for anonymous uses, but we'll release `share a page for external user` feature on #313.
Thank you!
