### ISSUE TITLE
a plan to merge to master branch about graph renderer using mermaid

### ISSUE THREAD

**Issue by lunardial** [crowi/crowi#161]
mermaid を使った graph rendering を楽しみにしております。
コミット履歴を拝見すると、2016/6 の feature-mermaid-graph が master ブランチにマージされていないようなのですが、マージ予定はございますでしょうか。

**Comment by sotarok** [comment]
mermaid のように inline text で graph かけるものは導入を考えています。
feature-mermaid-graph 通りに実装するかちょっと検討したまままだ merge に至っておりませんでしたが、もうちょっとアイデアを固めつつ実装しようかと思っています、
