### ISSUE TITLE
How to launch with sub-url (baseUrl) ?

### ISSUE THREAD

**Issue by yuki-takei** [crowi/crowi#162]
Question
----------

I want to use Crowi with sub-url (baseUrl) like `http://example.com/crowi/`.
How to config?

I guess this snippet is useful,

```javascript
app.route('/book')
  .get(function(req, res) {
    res.send('Get a random book');
  })
  .post(function(req, res) {
    res.send('Add a book');
  })
  .put(function(req, res) {
    res.send('Update the book');
  });
```
(from http://expressjs.com/en/guide/routing.html)

but doesn't Crowi use `app.route()` or `express.Router()`, does it?
Do we need large-scale modification for it?

**Comment by sotarok** [comment]
It is not supposed that launch Crowi with sub-path of the url.
It might not need a lot of changes but need to change the handle of the page path (of course it is used for the page name).
Moreover, currently there is no plan to correspond to that feature.
