### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Bakudankun** [crowi/crowi#169]
[Bakudankun/docker-crowi](https://github.com/Bakudankun/docker-crowi)をv1.5.3に更新しようと（`CROWI_VERSION`を書き換えるだけの簡単なお仕事）したのですが、
`npm install --unsafe-perm`の段階で

```
npm ERR! Linux 4.4.0-59-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--unsafe-perm"
npm ERR! node v4.7.2
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE

npm ERR! utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utf-8-validate@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the utf-8-validate package,
npm ERR! not with npm itself.
...
```

などと出て失敗します。
が、失敗した後でそのままもう一度`npm install --unsafe-perm`すると何故か通ります。

試しにnpm-shrinkwrap.jsonを削除してから実行すると一発で成功した（utf-8-validateは1.2.2になりました）ので、npm-shrinkwrap.jsonを更新していただければ良いのかな？と思います。

それともこれはインストール時にこちらで削除なりするべき物だったりするのでしょうか？

**Comment by sotarok** [comment]
npm-shrinkwrap はサブパッケージまで含めてバージョンを固定するために使っているので、本来は削除するべきもの、ではありません。で、shrinkwrap によって 1.2.1 が指定されていて 1.2.1 がインストールされようとするのは大丈夫なはずです。
また、各サブパッケージの依存が矛盾していないかも確認しましたが、どれも `1.2.x` が指定されていたので、そこは問題なさそうでした ...
また、まっさらな状態から 1.5.3 (node 4.73, npm 3.10.10) @ Debian jessie 8.7 で試してみましたが、インストール成功しました。
うーん、ちょっとわからないですね ...

**Comment by Bakudankun** [comment]
確かに、Docker HubのAutomated buildは相変わらず失敗しますが、Herokuでは成功しますし、ローカルPCで試すと成功するPCと失敗するPCがあったり（カーネルの違い？）、以前失敗していたローカルPCを今アップデートして試したら成功するようになっていたりと、やはりよくわかりませんね……

とりあえず何らかの形で1.5.3以上を`docker pull`できるようになったらcloseしようかと思います。
