### ISSUE TITLE
Want to delete comment (コメントの削除機能が欲しい)

### ISSUE THREAD

**Issue by hoboaki** [crowi/crowi#178]
コメントの削除機能がないためコメントの敷居が上がってしまっています。（例：間違って変な書き方をしたコメントが残り続けるのが怖い）

削除でも非表示でもいいので、何らかの形で一度投稿したコメントを見えなくする機能があると大変嬉しいです。

**Comment by sotarok** [comment]
Implemented on https://github.com/crowi/crowi/pull/734
