### ISSUE TITLE
Not available on IE11 (Internet Exploler 11で表示されない)

### ISSUE THREAD

**Issue by ymiyasaka** [crowi/crowi#187]
IEの機能制限に起因するものと思いますが、
IE11で表示されない症状があります。
Edge / Chrome / Firefoxでは表示されます。
デバッガを見ると ’Promise’は定義されていません .のメッセージ表示があります。
症状を解決していただけるとありがたいです。

**Comment by sotarok** [comment]
IE11に関しては私自身にも実行環境が無い＆今後の開発サポートと言う意味でも、おそらく完全なサポートは厳しいですね。。
他のブラウザをお使いいただくか、Pull Request いただければ取り込むことは可能です!

**Comment by abouthiroppy** [comment]
babel-polyfillを入れれば解決すると思います
