### ISSUE TITLE
コードハイライトの表示がおかしい

### ISSUE THREAD

**Issue by nukosuke** [crowi/crowi#201]
emojiの影響なのか、rubyのシンボルが謎のimgタグに変換されます。

[![https://gyazo.com/05c7f33ed9b905bfa2d6feb620e45a01](https://i.gyazo.com/05c7f33ed9b905bfa2d6feb620e45a01.png)](https://gyazo.com/05c7f33ed9b905bfa2d6feb620e45a01)

**Comment by suzuki** [comment]
これは、確かに emoji 変換の影響ですね。調査します。
