### ISSUE TITLE
コード内のインデントが消えてしまう

### ISSUE THREAD

**Issue by mumeiyamibito** [crowi/crowi#202]
コードをページに載せようとしているのですが、コードを「```」で囲んだところ、
インデントが消えて表示されました。
インデントをそのまま残すことはできないでしょうか？
なお、インデントはタブでも半角スペース×4でもダメでした。

**Comment by suzuki** [comment]
> インデントが消えて表示されました。
> インデントをそのまま残すことはできないでしょうか？

Crowi のデモサイトでは「インデントが消える」という状態を再現できませんでした。

- http://demo.crowi.wiki/user/suzuki/memo/2017/03/24/code

具体的にはどのようなコードを記載しようとしたのでしょうか？
公開可能な範囲で教えてください。

**Comment by mumeiyamibito** [comment]
@suzuki 返信ありがとうございます。
デモサイトで試したところ、確かにインデントは有効なようです。
自分のサイトでテストページとして確認しましたが、インデントが有効になっていました。

そこで、コード周囲の書式を確認したところ、どうやらリストによって字下げしたことが原因なようでした。
通常のリスト以下にコードを表示する場合は、正常にインデントが効いていますが、
レベル (字下げ) を変えたリストに属するコードではインデントが無効になるようです。
例えば、
<pre>
* code1 is shown below
```
code1
    indent
```
    * code2 is shown below
```
code2
    indent
```
</pre>
この時に、code1 内の indent は有効になっていますが、code2 内の indent が無効になっていました。

何か解決方法はありますでしょうか？

**Comment by suzuki** [comment]
なるほど、こちらでも再現しました。
現状では、上記の Markdown をうまく表示する方法は残念ながらなさそうです。

Crowi 内の「Markdown から HTML へのレンダリング処理」を修正すれば、あるいは解消するかも知れないので、確認してみます。

（GitHub でも、上記の Markdown はうまくレンダリングできないようですね）

**Comment by sotarok** [comment]
Markdown で再現するには、インデントをそこに合わせてあげる方法ですね

<pre>
* code1 is shown below
  ```
  code1
      indent
  ```
    * code2 is shown below
      ```
      code2
          indent
      ```
</pre>

本来的には、 Markdown の list 表現内におけるブロック表現は、

```
* ここのリスト内のブロック表現は
  ↑ ここにインデントをあわせてあげると良いはず
```

というように、頭をそろえてあげるのが文法だったような気もします

![image](https://cloud.githubusercontent.com/assets/29064/24347112/328ffec2-1312-11e7-92cc-c7b984a5e1cf.png)

**Comment by mumeiyamibito** [comment]
@sotarok アドバイスありがとうございます。
確かにそのルールで記述すると 4 スペースでインデントされます！
こちらの記法が間違っていたんですね。
ご指摘ありがとうございます。
