### ISSUE TITLE
Windows環境で起動した場合の画像ファイルのローカルパスの扱いについて

### ISSUE THREAD

**Issue by Tomasom** [crowi/crowi#217]
いつもお世話になっております。
掲題についてバグ報告&修正の指針です。
本来ならPRでご査収お願いできればと存じますが、
Unix環境に合わせた動きが逆によくわからないので
いい感じの修正をお願い致します。

## バグ内容
Windows環境で`crowi`を起動して、`FILE_UPLOAD=local`を指定しても
画像のコピー&ペースト及び画像を開くことができません。
(画像をlocalにアップロードすること、および削除はできます)

## 調査結果
デバッグしたところ、ページ編集時に画像をコピー&ペーストしたときに
以下の変数値のパスがバックスラッシュ表記でした。
```js
        // crowi/lib/routes/attachment.js のL35あたり
        if (deliveryFile.fileName.match(/^\/uploads/)) { //<="\uploads\attachment\5908bc1931072001b0dce496\4839173e8b4998d5c2f6d527f96a5612.png"のような値が入る
          debug('Using loacal file module, just redirecting.')
          return res.redirect(deliveryFile.fileName);
        } else {
          return res.sendFile(deliveryFile.fileName, deliveryFile.options);
       }
```

## 当座の修正方法

```js
// パスで\となっていたら、すべて/に置換。
+       deliveryFile.fileName = deliveryFile.fileName.replace(/\\/g, "/");
        if (deliveryFile.fileName.match(/^\/uploads/)) {
```

**Comment by sotarok** [comment]
なるほどなるほど。たしかにおこりますね。
他の箇所でも出来る限り `path` module をつかって path を扱ってはいるのですが、できていない箇所も多々あるかもしれないとはおもっています。
利用者環境はともかく、動作環境としては Windows は推奨していないので、出来る限り Linux 環境で稼働させていただいたほうが良いと思います ...

もしどちらでも動くようにした Pull Request をいただければ対応は可能ですが、私自身が対応することはありません、すみません 🙇

**Comment by EnduranceRun** [comment]
回答ありがとうございます。
>利用者環境はともかく、動作環境としては Windows は推奨していないので、出来る限り Linux 環境で稼働させていただいたほうが良いと思います ...

ですよね(苦)
自分たちのプロジェクトがcrowiさんに支えられているのは事実なので、
リリースを迎えた暁にはPRなど恩返しできれば幸いです。

**Comment by sotarok** [comment]
Merged by #219
