### ISSUE TITLE
ページ一覧ページ

### ISSUE THREAD

**Issue by tohutohu** [crowi/crowi#221]
150人程度のサークルで運用しています。  
現在ページが1300ページ位存在するのですが、それを一覧できるような専用ページがほしいです。

できればURLの階層ごとに折りたたんで表示して欲しいです。

**Comment by sotarok** [comment]
hmm ...
1300ページを一気に一覧したいということでしょうか。
基本的に `/` にアクセスすれば階層以下のページはすべて見ることができる、という思想で、なので、各ページのタイトルの `/` がクリックしやすくなってるんですよね

↓ここの `/`
![image](https://cloud.githubusercontent.com/assets/29064/26198774/58383b80-3c02-11e7-95aa-357c8b8be638.png)

で `/` は常に階層以下のページ一覧、と

![image](https://cloud.githubusercontent.com/assets/29064/26198831/88ddc9d0-3c02-11e7-946b-471ce182452e.png)

折りたためる view があるとよい、というのはたまに聞くので、そういうのは何か考えていますが、リストについては、一度 ↑ の使い方は確認していただけるとー

**Comment by sanukin99** [comment]
社内に導入を検討してます。
使い方を体系的にまとめている場所を見つけられなかったので、触りながら試行錯誤しているのですが、次の動きに戸惑っています。

user1：適当なページ（/user/admin1配下のメモページ）を開いて「Edit」→「Just me」で更新
user2：user1が変更したページはアドレスを打ち込んでも見られない
admin1：[/]で一覧を出しても、user1に変更されたページは表示されない。（直接アドレスを指定すれば見える）

user1が意図的か否かは問わず「Just me」にすることはあり得るとして理解しても、管理者であるadmin1がページ一覧を出しても見られないのはよく動きがわからないのですが、この挙動で合っているのでしょうか？

少なくとも管理者は公開範囲によらず全てのページを一覧化できるとよいのですが…。

**Comment by sotarok** [comment]
@sanukin99 これは、たしかに。
複数の仕様上の問題点が含まれます。

1. 他人が作成したページを `Just me` に変更することでテロができる (User A が作成したページを、User B が Just Me に変更して更新可能 (これ自体が問題のある仕様))
2. 一覧そうして変更されたページの granted user の問題
3. 一覧とページ単体の閲覧における権限チェックが granted user か creator か統一されていない

ちょっと仕様自体考えます。
(管理者が全ページ見えるべき、かというと、User A さんの Private なページは見えるべきではないと思いますので、その点においては、まあ現行仕様で良いかな、とはおもうのですが。)

**Comment by sanukin99** [comment]
@sotarok コメントいただきありがとうございます。
最後の括弧書きの部分はおっしゃるとおり、現行仕様で問題ないようにも思います。
ちょっと考えすぎかもしれませんが、慣れないユーザーが共有ページをうっかり「Just Me」に変更してしまい、みんなが「確かあったような気がするページがない」と騒ぎ出すところまで想像し、管理者（もしくはサーバーのrootユーザー）なら何とかしてくれる、という解決シナリオまで考えついたのですが、そんな「慣れない」ユーザーを考えるのは日本人の悪い癖である「細かすぎる配慮」なのかもしれません。

ご検討いただけると幸いです。
プログラミング技術のない私は、素晴らしいソフトウェアがよりよくなるように願うのみとなってしまい、申し訳ありません。
