### ISSUE TITLE
ショートリンク機能について

### ISSUE THREAD

**Issue by EnduranceRun** [crowi/crowi#223]
Slackにウィキのリンクを貼り付けると
日本語が含まれる場合、
URIエンコードにより長くなるので見栄えが悪くなります。
Shareable Linkを公開時にも使用できませんか。

**Comment by sotarok** [comment]
You can pick it up from the sidebar!

**Comment by sotarok** [comment]
![image](https://cloud.githubusercontent.com/assets/29064/26198566/6bb69ac2-3c01-11e7-81fa-47013f2de21b.png)
