### ISSUE TITLE
SESのリージョン選択オプション

### ISSUE THREAD

**Issue by ruihhh** [crowi/crowi#239]
日本だと'us-west-2'リージョンを使っている人が多い印象ですが
オプションで選択できるようにしてはどうでしょうか？：D

**Comment by sotarok** [comment]
SES のみのリージョン選択ではなく AWS を活用する機能全体の設定になってしまうのですが、管理画面から region の設定は可能です。
そういう意味ではなくて、でしょうか?

**Comment by yukimunet** [comment]
S3はap-northeast-1、SESはus-west-2を設定したい、ということではないでしょうか。

**Comment by ruihhh** [comment]
@yukimunet  その通りです。
S3はap-northeast-1、SESはus-west-2 と別々のリージョンを設定したいです。

**Comment by sotarok** [comment]
なるほど、たしかにそういう要件はありそうですね。
検討します

**Comment by sotarok** [comment]
Fixed on https://github.com/crowi/crowi/pull/595

Thank you!
