### ISSUE TITLE
検索が機能しない

### ISSUE THREAD

**Issue by yuukiclass** [crowi/crowi#242]
上部検索ボックスで検索をしてもうまく動いていないようです。
私のローカルに構築したページだけでなく、デモページでも同様の現象が起きているので
改善よろしくお願いいたします。

**Comment by FujiHaruka** [comment]
http://site.crowi.wiki/ の heroku ボタンからデプロイしても同様の現象が起きました。報告しておきます。
version 1.6.2 です。

**Comment by sotarok** [comment]
Could you please try to re-build index from admin page?
![image](https://user-images.githubusercontent.com/29064/28099282-74d24334-66f6-11e7-9f7f-e514d8e3552c.png)

**Comment by sotarok** [comment]
demo site was fixed by that operation

**Comment by FujiHaruka** [comment]
Thank you ! In my case, this works.
