### ISSUE TITLE
バグ: Firefoxで開いた編集画面からCtrl+(Shift+)Tabでブラウザタブを切り替えるとインデントが増減する

### ISSUE THREAD

**Issue by tats-u** [crowi/crowi#243]
# 環境
- ブラウザ: Firefox 54.0.1 (Chrome 59・IE11では問題なし)
- Crowiのバージョン: (投稿時(7/16 日本時間16時)のデモのバージョン)

# 再現手順
1. Firefoxで複数のタブを開く
2. タブの1つでWikiにアクセスし、適当なページの編集画面に入る
3. 編集画面のエディタをアクティブにする (エディタにフォーカスを合わせる)
4. Ctrl+Tab・Ctrl+Shift+Tabで前後のタブに切り替える (マウスクリックによるタブ切り替えでは再現しません)

# 症状
- Ctrl+Tabで次のタブに切り替えるとインデントが増える
- Ctrl+Shift+Tabで前のタブに切り替えるとインデントが減る

# 期待される動作
-  Ctrl+(Shift+)Tabでタブを切り替えてもインデントの増減が起こらない

# 注記
恐らくフロントエンドの仕様とFirefoxの仕様が噛み合わずに起こった結果だと思います。
https://github.com/crowi/crowi/blob/master/resource/js/crowi-form.js#L177
このあたりを中心にチェック及び修正をよろしくお願いします。

当初貴Wikiからフォークしたcrowi-plusでこのバグを確認しました (https://github.com/weseek/crowi-plus/issues/132) が、フォーク元の貴Wikiでもバグの確認が取れたため、こちらにもIssueを投げさせていただきます。

**Comment by tats-u** [comment]
ご対応ありがとうございます。デモ (http://demo.crowi.wiki) の方がまだ直っていないようですが、更新はされたのでしょうか。

**Comment by suzuki** [comment]
デモはまだ更新されていません。
v1.6.3 でリリースする予定で、下記の pull request にまとめていく予定になっています。
https://github.com/crowi/crowi/pull/246

この pull request の修正確認用にデプロイしている下記のサイトでは直っていると思います。
https://crowi-dev-pr-246.herokuapp.com/

**Comment by tats-u** [comment]
無事に直っていることが確認できました。ありがとうございました。
IE11・Chrome・Edgeでも今まで通り動きます。
