### ISSUE TITLE
npm install fails ( Failed to install npm-sass)

### ISSUE THREAD

**Issue by shinndo** [crowi/crowi#244]
リポジトリをクローンした後に `npm install` すると npm-sass のインストールに失敗するようです。

```
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.2/linux-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080
```

この状態で `npm start` でサーバーを立ち上げてブラウザからアクセスすると、CSSが適用されない状態でページが表示されます。（初回のユーザー作成はこの状態のまま成功することを確認しました）

![crowi_err](https://user-images.githubusercontent.com/4468752/28304606-52838798-6bd3-11e7-8e35-98bda33d51fc.png)

**Comment by abouthiroppy** [comment]
Nodeのバージョンを教えてほしいです。

**Comment by shinndo** [comment]
すいません、環境情報が抜けていました。
Nodeは最新の 8.1.4 になります。
最新のバージョンが問題かなと思い、6.10.0でも試してみましたが同様でした。

**Comment by sotarok** [comment]
Thank you for reporting.
This is caused by the locked version of the package.
Fixed by updating npm-shrinkwarp
