### ISSUE TITLE
APIによるページリスト取得

### ISSUE THREAD

**Issue by mougenko** [crowi/crowi#248]
Electronでクライアントアプリケーションの作成を考えているのですが、
ページリストをAPIで取得する方法があると大変たすかります。
(その他にもAPIが充実するとありがたいです)

**Comment by sotarok** [comment]
API としては、 `/_api/pages.list` で parameter に `path` を与えると path 以下のページがとれます!
(API はぜんぶ beta 扱いで変わっちゃうかもしれないからという理由で doc すら生成していないという体たらくで ... すみません)

**Comment by sotarok** [comment]
@mougenko それはともかく、Electron クライアント気になります! もし開発状況相談など変化ありましたら是非共有してください! & Gitter に部屋あるのでそちらもぜひ。
