### ISSUE TITLE
Nginxでリバースプロキシ時にログアウトできない

### ISSUE THREAD

**Issue by trisland** [crowi/crowi#253]
# 環境
- Crowi: 1.6.2
- node: v6.11.2
- npm: 5.3.0

# 再現手順
1. Crowiを3000番で起動させる
2. Nginxでリバースプロキシを施し、`http://127.0.0.1`からログイン
3. 右上メニューから`ログアウト`しても`http://127.0.0.1`にリダイレクトされログアウトできない

	## /etc/nginx/conf.d/crowi.conf
	
	Nginx用の設定ファイルです。
	
	```crowi.conf
	server {
		location / {
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header Host $host;
			proxy_pass http://127.0.0.1:3000;
			
			proxy_redirect off;
		}
	}
	```

# 症状
`http://127.0.0.1:3000`からログインした際はログアウトできるが、リバースプロキシ後に`http://127.0.0.1`からログインした際はログアウトできない

些細なことでもご教示賜れますと幸いです。

**Comment by abouthiroppy** [comment]
@suzuki この問題わかりますか？(crowi-developを開発していたので)

**Comment by suzuki** [comment]
@trisland `http://127.0.0.1/logout` に直接アクセスしてログアウトできますか？

**Comment by trisland** [comment]
@abouthiroppy @suzuki 様
ご返信いただきありがとうございます。

`http://127.0.0.1/logout` に直接アクセスした場合も、同様に`http://127.0.0.1/` にリダイレクトされログインしたままです。

**Comment by trisland** [comment]
@abouthiroppy @suzuki 様
ご返信いただきありがとうございます。

`http://127.0.0.1/logout` に直接アクセスした場合も、同様に`http://127.0.0.1/` にリダイレクトされログインしたままです。

**Comment by suzuki** [comment]
@trisland 手元の nginx -> crowi の構成で再現できずにいます（手元では動いています）

1. nginx の設定は `/etc/nginx/conf.d/crowi.conf` だけですか？
2. nginx のアクセスログ・エラーログになにか情報はありませんか？

通常動作時のアクセスログは以下のようになります。

```
172.19.0.1 - - [02/Sep/2017:22:53:47 +0000] "GET /logout HTTP/1.1" 302 46 "http://127.0.0.1/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36" "-"
```

**Comment by abouthiroppy** [comment]
ping @trisland

**Comment by trisland** [comment]
@abouthiroppy お返事が遅くなり申し訳ございません。

> 1.nginx の設定は /etc/nginx/conf.d/crowi.conf だけですか？

はい、`/etc/nginx/conf.d/crowi.conf`のみです。`/etc/nginx/conf.d/default.conf`は`/etc/nginx/conf.d/default.conf.org`にリネームしています。

`/etc/nginx`直下のファイルはどれも編集しておりません。
    
> 2.nginx のアクセスログ・エラーログになにか情報はありませんか？

`/var/log/nginx/access.log`には以下のように出力されておりますが、役に立つでしょうか…？

```
10.238.83.207 - - [19/Sep/2017:21:37:50 +0900] "GET /logout HTTP/1.1" 302 46 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36" "-"
```

どうぞよろしくお願いいたします。

**Comment by abouthiroppy** [comment]
Could you confirm this? /cc @suzuki

**Comment by sotarok** [comment]
追加でなにか確認できる現象がなければこちらは close とさせてください。

**Comment by trisland** [comment]
承知いたしました。
クローズいたします。
