### ISSUE TITLE
Want to search created private page conents(自分が作成した非公開ページの内容を検索できるようになってほしい)

### ISSUE THREAD

**Issue by dev-hayash** [crowi/crowi#260]
自分が作成したページであれば検索にヒットして欲しいです。

**Comment by sotarok** [comment]
Thank you for the request.

This would be discussed.
The feature only for private page can be imlemented, make it clear that the behavior of link-shared private page.

**Comment by sotarok** [comment]
Implemented https://github.com/crowi/crowi/pull/427 and will be released on 1.8.
