### ISSUE TITLE
Markdown helper is broken when using latest Chrome browser

### ISSUE THREAD

**Issue by suzuki** [crowi/crowi#261]
## About

- Using latest Chrome (Mac)
    - Version 61.0.3163.100 (Official Build) (64-bit)
- when input "list" of Markdown
    - wrong cursor position
        - wrong text selection
    - wrong indent with TAB  key or Shift + TAB key

## Reproduce

- Input `"-"` or `"*"` and `Return`
```
- aaa[return]
```

### Expected

```
- aaa
- [cursor position]
```

### Result

```
- aaa
[- ] <- text selected
```

**Comment by abouthiroppy** [comment]
I updated my chrome, and I can not confirm this issue.

**Comment by suzuki** [comment]
This is my browser's problem.
The `esarea` extention was enabled on my Chrome. When disabled it, fixed this problem.
