### ISSUE TITLE
Want to download with uploaded file name(アップロードしたファイル名でダウンロードしたい)

### ISSUE THREAD

**Issue by dev-hayash** [crowi/crowi#262]
![issue-262](https://user-images.githubusercontent.com/19341340/31168487-733c1c58-a930-11e7-96d3-5a32fb427a9f.png)
画像以外のファイルをページに添付できて便利なのですが、
ダウンロードすると、ファイル登録時のObjectID＋拡張子のファイル名で
ダウンロードされてしまいます。
アップロードした時のファイル名でダウンロードできると幸いです。

**Comment by sotarok** [comment]
I see, thank you for the feedback.
Will be updated in v1.6.3

**Comment by dev-hayash** [comment]
対応ありがとうございます。
修正ソースを取り込んでみたのですが、従来と変わらない状況です。
修正箇所を見ますと、[/files:id](https://github.com/crowi/crowi/blob/790edd9282827fcb75929de45875b0a0f5b4e562/lib/routes/index.js#L84)のパスを通過するときの処理のようなのですが、どのような操作を行うと、このパスを要求するのかご教示いただけないでしょうか。
