### ISSUE TITLE
Destination URL in a mail asking administrator for approval of new user registration is wrong

### ISSUE THREAD

**Issue by emadurandal** [crowi/crowi#263]
お世話になります。

ユーザー登録の承認を管理者に求めるメールで、
Please do some action with following URL: https://xxxx.xxxx.xxxx/admin/user
とあるんですが、実際はadmin/users なので、メールの方はURLにsが抜けているようです。

**Comment by sotarok** [comment]
Thank you for reporting the issue.
Fixed in v1.6.3
