### ISSUE TITLE
ページ内で table タグを利用すると、意図しない空行が入る

### ISSUE THREAD

**Issue by kaishuu0123** [crowi/crowi#264]
* はじめまして、markdown の簡単なメモとして crowi を利用させていただいています
* crowi で複雑なテーブルを記述するときに table タグを利用するのですが、空行が入ってしまうようです
    * 空行が入らないようにしていただくことは可能でしょうか
* 利用している環境は Windows 10、ブラウザは Chrome 61.0.3163.100 です
* 以下は再現手順です

## 再現手順
* 以下のようなページを作成する

```
# memo/2017/10/12
## Table tag test Pattern .1

<table>
  <thead>
    <tr>
      <th>th contents text</th>
    </tr>
  <thead>
  <tbody>
    <tr>
      <td>td contens text</td>
    </tr>
  </tbody>
</table>

## Table tag test Pattern .2

<table>
  <tr>
    <th>th contents text</th>
    <td>td contents text</th>
  </tr>
</table>
```

## 症状
* demo の crowi にページを作成しました
    * http://demo.crowi.wiki/user/kaishuu0123/memo/2017/10/12
* 上記のページのようにヘッダとテーブルの間に意図しない空行が入る

**Comment by sotarok** [comment]
これはご指摘の通り、意図していない挙動 & バグです。
markdown のレンダリングライブラリを入れ替えるつもりでもいますので、その点でちょっと変更を検討していきます 🙇

**Comment by sotarok** [comment]
I confirmed this was fixed on latest master.
Thank you for report it!
