### ISSUE TITLE
XSSが可能となっています

### ISSUE THREAD

**Issue by Himenon** [crowi/crowi#266]
はじめまして。crowiの導入を検討しようとして、XSSを試したところ、通ってしまいました。

編集画面と、編集完了後のページでのXSSが確認されています。

```
<script>for (let i=1;;++i) {alert(Array(i+1).join("Hello XSS!"));}</script>
```

どこのコードが問題の箇所か特定できていませんが、早急に修正したほうが良いと思います。
また、デモの方でも同じような症状がでています。

`http://demo.crowi.wiki/`

**Comment by sotarok** [comment]
Thank you for the feedback.
Please refer following PR https://github.com/crowi/crowi/pull/97

**Comment by Himenon** [comment]
既にclosedされてあったんですね、見落としていました＾＾：
ありがとうございます。

**Comment by sotarok** [comment]
こちらこそ、ありがとうございます。引き続きお願いします 🙇
