### ISSUE TITLE
Mathjaxの下付き文字のアンダースコアがMarkdownの強調と解釈されて、数式が正しく表示されない

### ISSUE THREAD

**Issue by paruma** [crowi/crowi#269]
タイトルの通りで、次のようになります。 crowiのバージョンは1.6.3です。
```markdown
$a_{i+1}$

$(a_i)_{i=1}^n$

$a_{i+1} = b_j$

$a_{i+1} = b_{j+1}$
```
![image](https://user-images.githubusercontent.com/19905365/34496425-e0708748-f03c-11e7-8b91-f5a85336d445.png)

`*`でも同様のことが起こります。(例えば、`$a*b = b*a$`)

**Comment by sotarok** [comment]
Ah ... this would be happened.
Hmm, let me think how to fix it.
