### ISSUE TITLE
AWS s3設定後にファイルアップロードすると、Hostname/IP doesn't match certificate's altnames

### ISSUE THREAD

**Issue by nishiyamaosamu** [crowi/crowi#270]
crowi@1.6.3
node v6.12.3
npm  v3.10.10
https://github.com/crowi/docker-crowi を利用して、docker-composeを使っています。

管理画面からs3のアクセストークン設定し、FILE_UPLOAD=awsとして再起動し、ファイルアップロードしようとすると以下のエラーが発生しております。

```
crowi_1          | Error: Hostname/IP doesn't match certificate's altnames: "Host: my-bucket-name.s3.amazonaws.com. is not in the cert's altnames: DNS:*.s3.amazonaws.com, DNS:s3.amazonaws.com"
crowi_1          |     at Object.checkServerIdentity (tls.js:199:17)
crowi_1          |     at TLSSocket.<anonymous> (_tls_wrap.js:1098:29)
crowi_1          |     at emitNone (events.js:86:13)
crowi_1          |     at TLSSocket.emit (events.js:185:7)
crowi_1          |     at TLSSocket._finishInit (_tls_wrap.js:610:8)
crowi_1          |     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```

ググってみたところでは、以下のQAが参考になりそうですが、
https://stackoverflow.com/questions/14262986/node-js-hostname-ip-doesnt-match-certificates-altnames

どのような解決方法が適切か？またこの問題は私の環境下のみの問題かどうか確認させてもらえればと思います。

（すばらしいOSSをありがとうございます！活用させていただきますmm）

**Comment by nishiyamaosamu** [comment]
https://github.com/crowi/crowi/blob/master/local_modules/crowi-fileupload-aws/index.js#L86
ここのところが
`https://s3-ap-northeast-1.amazonaws.com/my-bucket-name/` のようにしたらよいのかもですね。追って確認してみます。

**Comment by sotarok** [comment]
なるほど ...
手元では動いているのですが、たしかに `https://s3.amazonaws.com/my-bucket-name/` のほうが安全かもしれませんね。

ちなみに aws の config は4項目すべて埋めてある、という状況ですよね？
また、bucket 名は、正しくその api key でリクエスト可能な bucket 名は指定されている、で間違いないでしょうか?

**Comment by nishiyamaosamu** [comment]
ご返信ありがとうございます。お伝え不足でしたが、アップロードまでは完了している状態でした。aws s3は正常に動いているものの、nodejs側でエディタからリクエストする時にエラーになるような状態です。
nodejsの0.9.2以降でこのDNSのチェックが入るようですが、 @sotarok さんの環境はnodejsバージョンがそれ以下ということでしょうか？

**Comment by sotarok** [comment]
@nishiyamaosamu こちらすっかり返信しておりませんでした。
手元では Crowi の環境手順どおり 8.x (v1.6 系であれば 6.x) で可動させています。
ちょっと再現手順がないので、もし追加で確認できる現象がなければ close とさせてください。
