### ISSUE TITLE
Error on searching

### ISSUE THREAD

**Issue by sp4ghet** [crowi/crowi#278]
https://github.com/crowi/crowi/issues/120#issuecomment-351326856

Seeing the same error as the above comment in #120 reproducing on Crowi 1.6.0 on heroku 

I figured I would make a new issue instead of continuing on a closed thread.

**Comment by ogiekako** [comment]
Any update on it?

**Comment by sp4ghet** [comment]
Not yet..it looks like the there are search queries being run on Bonsai, and Bonsai thinks everything is fine, so it probably has something to do with accepting the search results in Crowi-side. 

I'd love to go take a look but I'm not familiar with the codebase to know where would be relevant..

**Comment by sotarok** [comment]
I found that the reason of this issue.
It is because of changes of Bonsai, they set v6.x as the default version of ES and mappings.json of Crowi doesn't comply the version of v6.x.
I'll consider to handle this.

**Comment by sp4ghet** [comment]
God Bless :tada:

**Comment by sp4ghet** [comment]
@sotarok I still see this on a new heroku deployment.
![image](https://user-images.githubusercontent.com/8775460/40290710-cfe8acae-5cfa-11e8-91c7-828b5735babf.png)

**Comment by sotarok** [comment]
@sp4ghet Did you try it out with already launched Crowi?
The version written in `app.json` is used when the first time Crowi build on heroku.

So, to fix it, try belows:

- Remove Bonsai add-on from your running Crowi.
- Add Bonsai add-on manually with `5.6` version.
    - [ref.](https://docs.bonsai.io/docs/elasticsearch-version-management)

**Comment by sp4ghet** [comment]
I tried by creating new instance in heroku using "Deploy on Heroku" button on the README

I will also try applying this to the existing one. Thanks!

**Comment by sp4ghet** [comment]
Doing the manual addon creation fixed the search on the existing instance, which solves my problem! Thank you!!
