### ISSUE TITLE
稼働中の環境からPASSWORD_SEEDを抽出する

### ISSUE THREAD

**Issue by ymfj** [crowi/crowi#284]
こちら(https://github.com/kajiken/docker-crowi)のDockerfile から運用を開始してしまったのですが，アップグレードしようとしたタイミングで，PASSWORD_SEEDを把握せずに運用を開始してしまっていることに気づきました．現在稼働中の環境の，PASSWORD_SEEDをあとから抽出することは可能でしょうか？

助けていただけると幸いです．

**Comment by sotarok** [comment]
@ymfj 実行中のプロセスに対して後から抽出することはできないのですが、指定していないのであれば、おそらく `PASSWORD_SEED` は `undefined` という文字列になっている気がします

**Comment by ymfj** [comment]
ありがとうございます．``undefined``で試してみたのですがだめでした．
SEEDは取り出せる形では保持されていないのですね．承知しました．

最後の手段として，新しいSEED環境で新規登録を行って，PADDWORD->ハッシュ値の対応を得た後，すべてのユーザのパスワードをDB上で直接書き換えてやろうと考えています．（幸い運用上これで対応可能なので）

**Comment by sotarok** [comment]
そうでしたか。残念です…
https://github.com/crowi/crowi/blob/master/bin/password-hash-generator.js
こちらでhashは作れますのでお試しくださいー
