### ISSUE TITLE
docker-compose の初回起動がUnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)で失敗する

### ISSUE THREAD

**Issue by himrock922** [crowi/crowi#308]
初めまして。日本語での相談でも大丈夫でしょうか?

## 構築環境のリソース

```
OS: macOS High Sierra
メモリ: 8GB 1600 MHz DDR3
CPU: 1.8 GHz Intel Core i5
```

上記の環境でdocker-compose経由で開発環境の構築を試みました。

```
% docker-compose -f docker-compose.development.yml up -d                                                  (git)-[master]
Creating crowi_elasticsearch_1 ... done
Creating crowi_plantuml_1      ... done
Creating crowi_redis_1         ... done
Creating crowi_mongodb_1       ... done
Creating crowi_crowi_1         ...

ERROR: for crowi_crowi_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

ERROR: for crowi  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

crowiコンテナの構築に時間がかかっており、初回構築に失敗します。
なお、2回目以降の
`docker-compose -f docker-compose.development.yml up -d` であれば、起動に成功しました。

軽微な修正ではありますが、 `.env` ファイルに以下の環境変数を追加すれば初回でも起動に成功します。

```
% vim .env.sample
(中略)
PORT=3000
+ COMPOSE_HTTP_TIMEOUT=120
```

```
% cp .env.sample .env
% docker-compose -f docker-compose.development.yml up -d
Creating crowi_plantuml_1      ... done
Creating crowi_mongodb_1       ... done
Creating crowi_elasticsearch_1 ... done
Creating crowi_redis_1         ... done
Creating crowi_crowi_1         ...
```

こちら.env.sampleに `docker-compose` 用の環境変数の追加の修正をPRとして送っても良いでしょうか?

**Comment by himrock922** [comment]
返信ありがとうございます。
取り急ぎ、回答します。

> envにはアプリケーションで利用する環境変数のみを入れておきたいかなと思います。
こちらは僕も同意見です。

> .envの中身がホストに環境変数として展開されているのも気になるのですが、 export $(cat .env) などを実行されていたりしますか？(違っていたらすみません)
こちらは実行しておりません。

> 
こちらの環境では再現できなかったのですが、初回起動時に60秒以上かかるということなので、それをどうにか短くできると嬉しいのですが・・・。
docker-compose -f docker-compose.development.yml --verbose up で、タイムアウト時のより詳しい情報を得ることは出来ますか？

```
(中略)
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.feed_queue: Pending: set()
compose.parallel.parallel_execute_iter: Failed: ServiceName(project='crowi', service='crowi', number=1)
compose.parallel.feed_queue: Pending: set()

ERROR: for crowi_crowi_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
compose.parallel.parallel_execute_iter: Failed: <Service: crowi>
compose.parallel.feed_queue: Pending: set()

ERROR: for crowi  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
ERROR: compose.cli.errors.log_timeout_error: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

中略していますが、 `compose.parallel.feed_queue` がloopしてしまっています。
https://github.com/docker/for-mac/issues/2153

私のMac Book AirのDockerのversionです。↓
![2018-06-29 12 40 31](https://user-images.githubusercontent.com/4998536/42072079-b69209ae-7b99-11e8-9a9e-93b082dd5eb8.png)

まだちゃんと調べきれていないですが、 `crowi`  の問題と言うよりかは `Docker Engine` の問題に近いような気がしてきました。

取り急ぎ連絡です。

**Comment by lightnet328** [comment]
私のOSもMacでDocker for Macのバージョンもhimrock922さんと同じ環境のようです。
そうですね、Issueを見るとDocker for Macで起こる問題だと感じます。
原因が特定できていない上に再現もできていないのでCrowi側としては対応するのが少しむずかしいかなと・・・。

**Comment by himrock922** [comment]
ありがとうございます。
僕としても、Docker for Macの問題はDocker for Macで解決するべきだし、この話は忘れていただけますと幸いです。
大変失礼しました。

因みに、 crowi の開発フローがちょっと分からなかったので、この後の対処法を教えていただきたいのですが、このissueは僕の方で閉じちゃっても大丈夫ですか?
もともと、自分がまいた種ですし、issue作成者が閉じるのが筋かなと、、、

**Comment by lightnet328** [comment]
いえ、合意が得られてよかったと思います。
はい、閉じていただいて構いません。

**Comment by himrock922** [comment]
ありがとうございます。ではこのissueは閉じます。
