### ISSUE TITLE
Herokuへのデプロイが失敗する

### ISSUE THREAD

**Issue by sonnyky** [crowi/crowi#324]
v1.6.4のRelease版を持ってきて、Heroku に入っている古いCrowiをアップデートしようとしたら、
以下のエラーで失敗しました。

>  [06:47:45] Using gulpfile /tmp/build_f13e7f29c21408c3f6349baf038cd39b/gulpfile.js
remote:        [06:47:45] Starting 'css:sass'...
remote:        [06:47:45] Starting 'js:del'...
remote:        [06:47:45] 'js:del' errored after 495 μs
remote:        [06:47:45] Error: ENOENT: no such file or directory, scandir './public/js'
remote:        at Error (native)
remote:        at Object.fs.readdirSync (fs.js:961:18)
remote:        at Gulp.<anonymous> (/tmp/build_f13e7f29c21408c3f6349baf038cd39b/gulpfile.js:74:24)
remote:        at module.exports (/tmp/build_f13e7f29c21408c3f6349baf038cd39b/node_modules/orchestrator/lib/runTask.js:34:7)
remote:        at Gulp.Orchestrator._runTask (/tmp/build_f13e7f29c21408c3f6349baf038cd39b/node_modules/orchestrator/index.js:273:3)
remote:        at Gulp.Orchestrator._runStep (/tmp/build_f13e7f29c21408c3f6349baf038cd39b/node_modules/orchestrator/index.js:214:10)
remote:        at Gulp.Orchestrator.start (/tmp/build_f13e7f29c21408c3f6349baf038cd39b/node_modules/orchestrator/index.js:134:8)
remote:        at /tmp/build_f13e7f29c21408c3f6349baf038cd39b/node_modules/gulp/bin/gulp.js:129:20
remote:        at _combinedTickCallback (internal/process/next_tick.js:73:7)
remote:        at process._tickCallback (internal/process/next_tick.js:104:9)
remote:        [06:47:45] Finished 'css:sass' after 404 ms
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno 1
remote:        npm ERR! crowi@1.6.4 postinstall: `gulp`
remote:        npm ERR! Exit status 1
remote:        npm ERR!
remote:        npm ERR! Failed at the crowi@1.6.4 postinstall script.
remote:        npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
remote:
remote:        npm ERR! A complete log of this run can be found in:
remote:        npm ERR!     /tmp/npmcache.4Rn5X/_logs/2018-08-14T06_47_45_744Z-debug.log
remote:
remote: -----> Build failed

**Comment by sonnyky** [comment]
gulpfile.js が新しくなると失敗し、古いままだと問題なくデプロイできます。

以下の内容なら成功します。

> gulp.task('js:del', function() {
  var fileList = [
    js.dist,
    js.bundled,
    js.admin,
    js.form,
    js.presentation,
    js.app,
  ];
  fileList = fileList.concat(fileList.map(function(fn){ return fn.replace(/\.js/, '.min.js');}));
  return del(fileList);
});

**Comment by sotarok** [comment]
@sonnyky すみませんこちら再現できていません
`js:del` に失敗しているようですが、 `./public/js` というディレクトリがなくなっているように見えます。
コレは本来 git repository に含まれているので消えることはなさそうなのですが。

**Comment by sonnyky** [comment]
@sotarok 
こちらの手違いでGitignore に入っていました。失礼しました。
