### ISSUE TITLE
ユーザーページ Favorite欄、個別ページで強調されるユーザーが異なる

### ISSUE THREAD

**Issue by otofune** [crowi/crowi#335]
Favorite 欄では更新者が、個別ページでは作成者が強調されています。
なにか意図があるのでしょうか？

**Comment by sotarok** [comment]
favorite 欄というか、list 表示では更新者を出しています、これは更新された順に並んでいるからです。
favorite 欄では、その共通UIをつかっているので、更新順じゃないけど更新者のアイコンになる、というのはたしかにありますね。
個別ページは一応ページのオーナー的存在として作成者が大きく表示されています。

**Comment by otofune** [comment]
ありがとうございました
