### ISSUE TITLE
Can't login after reboot server

### ISSUE THREAD

**Issue by rluisr** [crowi/crowi#337]
Hi crowi team.

When I reboot server which running crowi, I can't login into that but it can access login page.
Where is the log dir?

**Comment by sotarok** [comment]
Logs are written to STDOUT so you can catch them with it.
And if you can edit your ENVs, add `DEBUG=crowi:*` and you can catch debug logs.

**Comment by sotarok** [comment]
> Aug 24 14:36:28 crowi node: Fri, 24 Aug 2018 05:36:28 GMT crowi:routes:login on login findUserByEmailAndPassword null null

This log exports `err` and `userData`, if the user logged in successfully, the following log should be output:

```
2018-08-25T10:25:08.881Z crowi:routes:login on login findUserByEmailAndPassword null { _id: 56d681ee8a260d6a0712f265,
  ...
  lang: 'en-US' }
```

First, please make sure your `PASSWORD_SEED` env is same as the one you run before.
If `PASSWORD_SEED` you specified on current env is not same as the previous one, user will not be able to log in.

If you update your password forcibly, you can use `password-hash-generator` tool and then update data on Mongo directly.

1. Get hashed password with the tool:

```
$ node bin/password-hash-generator.js --seed="your password seed" --password="your password"

XXXXX (the hashed password)
```

2. Then access to your MongoDB to update it like following query:

```
db.users.update({ email: 'your email' }, {$set: { password: "XXXXX (the hashed password)"}});
```

**Comment by rluisr** [comment]
Thanks. worked perfectly.
