### ISSUE TITLE
Anacondaを使って実行すると、crowiをビルドできない

### ISSUE THREAD

**Issue by Takashi-Aihara** [crowi/crowi#376]
現在、windows 環境にcrowi をインストールしようとしているのですが、「npm install」を実行した場合のエラーが消えずに困っております。
また、(※１)￥を参考にcrowiを起動するとcssなどが適用されず、HTMLファイルのみが表示される状況になっております。
どなたか、ご存知の方がいればご共有いただけると幸いです。

【環境】
`OS: Windows64bit`
`Python: Anaconda Python3.6`
`node.js: 6.4.1`
`mongoDB: v4.0.4`
`crowi: crowi-1.7.4`

【状況】
※１の「ビルドする」でエラー発生。下記エラーメッセージ
```
gyp ERR! stack Error: Command failed: C:\ProgramData\Anaconda3\python.exe -c import sys; print "%s.%s.%s" % sys.version_
info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:5)
```
（※2）をすべて試しましたが、エラーが消えませんでした。

（※１）
[https://cfm-art.sakura.ne.jp/sys/archives/912](https://cfm-art.sakura.ne.jp/sys/archives/912)
（※２）
[http://overmorrow.hatenablog.com/entry/2015/11/27/235935](http://overmorrow.hatenablog.com/entry/2015/11/27/235935)
（※３参考）
[https://qiita.com/nooby/items/9b197c2b666d6b8371e1#node%E3%81%AE%E8%A8%AD%E5%AE%9A](https://qiita.com/nooby/items/9b197c2b666d6b8371e1#node%E3%81%AE%E8%A8%AD%E5%AE%9A)

**Comment by lightnet328** [comment]
上記のエラーはnode-gypによるものだと思います。
node-gypはPython 3系をサポートしていないため、Python 2系をご使用ください。
https://github.com/nodejs/node-gyp#installation

また、Crowi v1.7.4の開発環境はNode.js 8.11.2とMongoDB 3.6.3を使用しているため、同じバージョンを使用されたほうが不都合が少ないかと思います。

**Comment by Takashi-Aihara** [comment]
ご返信ありがとうございます。
python2系をダウンロードすると、次に下記のようなエラーが出たのですがご存知でしょうか。
「set NODE_ENV=production」を行ったのですが、エラーが消えず。。。

`'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crowi@1.7.4 prod:client: `NODE_ENV=production webpack --bail --colors --display-error-details --config tools/we
bpack.config.js``

> 上記のエラーはnode-gypによるものだと思います。
> node-gypはPython 3系をサポートしていないため、Python 2系をご使用ください。
> https://github.com/nodejs/node-gyp#installation
> 
> また、Crowi v1.7.4の開発環境はNode.js 8.11.2とMongoDB 3.6.3を使用しているため、同じバージョンを使用されたほうが不都合が少ないかと思います。

**Comment by lightnet328** [comment]
`SET variable=string` の構文で環境変数を定義する `cmd.exe` では、 `NODE_ENV=production` を環境変数の定義として解釈できません。
動作を確認しているわけではありませんが、下記の記事で挙げられている、Windowsで動作するBashのエミュレーターのGit BASHであれば解釈できるかと思います。
CrowiをWindowsにインストールする - https://cfm-art.sakura.ne.jp/sys/archives/912

**Comment by Takashi-Aihara** [comment]
Git Bash で行ったのですが、上部と同じエラーが消えず。。。
ほかに何か解決策があればご教授いただけると幸いです。

> `SET variable=string` の構文で環境変数を定義する `cmd.exe` では、 `NODE_ENV=production` を環境変数の定義として解釈できません。
> 動作を確認しているわけではありませんが、下記の記事で挙げられている、Windowsで動作するBashのエミュレーターのGit BASHであれば解釈できるかと思います。
> CrowiをWindowsにインストールする - https://cfm-art.sakura.ne.jp/sys/archives/912

**Comment by cfm-art** [comment]
横からすみません。
試してはいませんが、**cross-env** を利用してみてはどうでしょうか？
おそらくcmd.exeでもgit bashでも動くのでは無いかと思います。

### cross-envをインストール
npmで足します。

```bash
npm install cross-env
```

### scriptsを書き換える

`NODE_ENV=` を `cross_env NODE_ENV=` に書き換えます。

```json:package.json
{
  "name": "crowi",
  "version": "1.7.4",
  "description": "The simple & powerful Wiki",
 :
 略
 :
  "scripts": {
    "start": "node app.js",
    "dev": "concurrently --kill-others \"npm run dev:server\" \"npm run dev:client\" \"npm run watch\" ",
    "dev:server": "DEBUG=crowi:* cross_env NODE_ENV=development nodemon --watch ./lib/ --watch ./locales/ --ext 'js,json' --exec node app.js",
    "dev:client": "cross_env NODE_ENV=development webpack --progress --profile --colors --display-error-details --watch --config tools/webpack.config.js",
    "flow": "flow",
    "format": "eslint --fix \"**/*.js\"",
    "lint": "eslint \"**/*.js\"",
    "test": "mocha -r test/bootstrap.js --globals chai --reporter dot test/**/*.test.js --timeout 10000",
    "build": "npm run prod:client",
    "prod:client": "cross_env NODE_ENV=production webpack --bail --colors --display-error-details --config tools/webpack.config.js",
    "webpack": "webpack",
    "watch": "onchange \"**/*.js\" -e \"bin\" -e \"client/thirdparty-js\" -e \"node_modules\" -e \"public\" -f add -f change -- eslint --fix \"{{changed}}\"",
    "postinstall": "npm run build"
  },
 :
 略
 :
}

```

**Comment by lightnet328** [comment]
しばらくの間、やり取りがないため、このIssueをCloseします。
追加のやり取りが必要であれば、このIssueを再度Openしてご質問ください。
