### ISSUE TITLE
how to create a new plugin

### ISSUE THREAD

**Issue by Chen-Michael** [crowi/crowi#403]
I wanna expand the crowi, how can I do it?

I don't want to modify the existing code.

**Comment by sotarok** [comment]
hmm, there no way to expand Crowi pluggabe without modifying its codes.
But anyway, we think implementing those kind of mechanisms to extend Crowi like plugins in future.

**Comment by sotarok** [comment]
Plugin mechanism is to be developed and inform later.
Close this issue at this moment.
