### ISSUE TITLE
bin/search.js `Error TypeError: Cannot read property 'errors' of undefined`

### ISSUE THREAD

**Issue by k2wanko** [crowi/crowi#408]
`bin/search.js` produces an error.
https://github.com/crowi/crowi/blob/514871c75e71c1eec9cf6447c47c763fe2c0f4a4/bin/search.js

```
node bin/search.js add-pages
```

Error message

```
Error TypeError: Cannot read property 'errors' of undefined
```

However, the addition of page succeeded.

**Comment by sotarok** [comment]
Oh, you're right ... `bin/search.js` doesn't follow the change of `util/search.js`.
I'll check it.
And please

**Comment by k2wanko** [comment]
Thank you for checking.

I did not have permission to access the administration, I needed `bin/search.js`.
Although error is outputted, it was working, so I'm not in a hurry.
