### ISSUE TITLE
Question: Are there any "official" Docker images?

### ISSUE THREAD

**Issue by tomoyat1** [crowi/crowi#411]
Although there is a `Dockerfile` found in the repo, I cannot seem to find an official pre-build Docker image anywhere.

I am having to maintain my own Docker images because of this.

Are there any plans to put an official Docker image on Docker Hub (or any registry of you choice).
If not, then are there any reasons not to do so?

**Comment by otofune** [comment]
Thank you. But it have already done, you can use this. https://hub.docker.com/r/crowi/crowi.
Also, I think our image isn't easy to find now.
I'll add the hyperlink to it. Thank you!

**Comment by tomoyat1** [comment]
Ah, thanks!
