### ISSUE TITLE
スマートフォン表示の横幅の修正希望

### ISSUE THREAD

**Issue by Ogurana17** [crowi/crowi#434]
Deploy to Herokuで運用してます。
使ってみて気になったので投稿させていただきました。

スマートフォン表示にすると横幅が広くなる時があります。

1. 右端の空白（常に）
2. 長いURLを貼り付けた時

1つ目の空白スクロールバーのサイズかなぁと思います。

2つ目は`.wiki a{word-break:break-all}`で上手く行きました。（ページを作る度にstyleタグで記述してます）

crowi大好きです。
よろしくお願いいたします。

**Comment by Ogurana17** [comment]
.crowi.main-container .main article header{width:100%}を.crowi.main-container .main article header{width:100vw}に変更することで右端の空白は消えました。

**Comment by sotarok** [comment]
フィードバックありがとうございます！
折返し処理によって表示がずれる問題確かに以前から発生していますね。

対応検討します！

**Comment by Ogurana17** [comment]
>.crowi.main-container .main article header{width:100%}を.crowi.main-container .main article header{width:100vw}に変更することで右端の空白は消えました。

Chromeのデベロッパーツールで`.crowi.main-container .main article header.affix{width:100%}`を`.crowi.main-container .main article header.affix{width:100vw}`に変更でした。

申し訳ありません。

**Comment by sotarok** [comment]
@Ogurana17 Wiki page のほうは一旦 break-word として対応しました。
右の空白確かにちょっと気になるのですが、`vw` にすると他の条件のときに意図しない見た目になったりもしたので、一旦別の方法を考えてみることにします。

そもそもスマホ向けは全体的にイマイチなのでトータルで考えるときにまとめて対応する形で、一旦は 1.7.7 リリースと共に close させていただきます。
