### ISSUE TITLE
Optimize docker image

### ISSUE THREAD

**Issue by inductor** [crowi/crowi#445]
At the moment the crowi docker image size is over 1GB(more precisely 1.16GB).

I think it can be shrunk by doing the followings.

- Asset compile should be done before the server daemon starts.
	- Use multi-stage build so that you won't need `devDependencies` in production build.
- Use alpine node image for production running.
	- For asset compiling you can still use the debian based image.
- untrack unnecessary files in .dockerignore
	- .git
	- pre-complied asset files
	- test codes
	- other setting files such as elastic search and .circleci

**Comment by inductor** [comment]
I can contribute with the docker-wise problems, but I will probably need your help for asset compiling.

**Comment by lightnet328** [comment]
Thank you for the great advice! I created a PR related to this issue.
I didn't ignore test codes and setting files. This is because I think text files like codes and settings size are not so big.
Please review this PR, if it's OK with you.

**Comment by inductor** [comment]
Oops I closed the issue by mistake
