### ISSUE TITLE
List Crowi team as a contributor on GROWI

### ISSUE THREAD

**Issue by mizozobu** [crowi/crowi#454]
Hi Crowi team,

We are developing a new feature to list contributors on GROWI. See more details on https://github.com/weseek/growi/issues/1045.

We would like to recognize and give special thanks to Crowi team and list Crowi team under "Special Thanks". If you have a preferred name or prefer not to be listed, we are more than happy to accommodate your request. We would like to hear back from you by 6/17.

Regards,
GROWI team

**Comment by sotarok** [comment]
@mizozobu 
Thank you for inform us to note our project on your contributor list.
Crowi has a lot of contributor in past (of course it includes current Growi member :)).
I think it is enough that you already listed as `Crowi Team` on your special thanks list.

Thank you very much :)

**Comment by mizozobu** [comment]
Crowi team will be listed under "Special Thanks" on GROWI contributor list.
Thank you 👍
