### ISSUE TITLE
Deploy to Herokuボタンを押すとmasterブランチからデプロイされる

### ISSUE THREAD

**Issue by Bakudankun** [crowi/crowi#58]
リポジトリのREADMEやsite.crowi.wikiにあるDeploy to Herokuボタンを押すとmasterブランチのコードでHerokuにデプロイされるようです。

どのようにするのが良いかはわかりませんが、次のリリースの時（v1.3.1だと有料のアドオンを使うようなので）にでも[タグを指定](https://devcenter.heroku.com/articles/heroku-button#using-a-custom-git-branch)するか、masterにpush即リリースの運用に変更するか……しておいた方が良いと思います。

**Comment by sotarok** [comment]
これは、そのとおりですね。
次のバージョンリリースの際には、template parameter に version 指定の tree を指定するようにします！

**Comment by sotarok** [comment]
Fixed on  #73
