### ISSUE TITLE
npm install fails on windows

### ISSUE THREAD

**Issue by Steve-Mcl** [crowi/crowi#605]
I have tried downloading master and a release (V1.7.9).

I cannot get it to run.

On my last attempt, after following instructions [here](https://github.com/crowi/crowi/wiki/Install-and-Configuration) when i run `npm install` I get...

```
c:\crowi-1.7.9>npm install

> node-sass@4.12.0 install c:\crowi-1.7.9\node_modules\node-sass
> node scripts/install.js

Cached binary found at C:\ProgramData\npmglobal-cache\node-sass\4.12.0\win32-x64-64_binding.node

> core-js@2.6.9 postinstall c:\crowi-1.7.9\node_modules\@babel\runtime-corejs2\node_modules\core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> node-sass@4.12.0 postinstall c:\crowi-1.7.9\node_modules\node-sass
> node scripts/build.js

Binary found at c:\crowi-1.7.9\node_modules\node-sass\vendor\win32-x64-64\binding.node
Testing binary
Binary is fine

> nodemon@1.19.1 postinstall c:\crowi-1.7.9\node_modules\nodemon
> node bin/postinstall || exit 0


> crowi@1.7.9 postinstall c:\crowi-1.7.9
> npm run build


> crowi@1.7.9 build c:\crowi-1.7.9
> npm run prod:client


> crowi@1.7.9 prod:client c:\crowi-1.7.9
> NODE_ENV=production webpack --bail --colors --display-error-details --config tools/webpack.config.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crowi@1.7.9 prod:client: `NODE_ENV=production webpack --bail --colors --display-error-details --config tools/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crowi@1.7.9 prod:client script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\ProgramData\npmglobal-cache\_logs\2019-10-03T10_11_32_360Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crowi@1.7.9 build: `npm run prod:client`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crowi@1.7.9 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\ProgramData\npmglobal-cache\_logs\2019-10-03T10_11_32_407Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! crowi@1.7.9 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the crowi@1.7.9 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Is there some pre-reqs I need other than listed in the documentation? 

Could you guild me how to run crowi locally from SRC and from release?

Thanks, Steve.

**Comment by Steve-Mcl** [comment]
so I realise I have to install webpack (not certain why this didnt install as dev dependancy).

Also, I suspect this line `crowi@1.7.9 prod:client: `NODE_ENV=production webpack --bail --colors --display-error-details --config tools/webpack.config.js` should be separated by CRLF

I have now manually tried running `webpack --bail --colors --display-error-details --config tools/webpack.config.js` however I now get the error `ModuleNotFoundError: Module not found: Error: Can't resolve '../locales/en/translation.yml' in 'c:\crowi-1.7.9\client'`

Looking in `../locals` there is no directory called `en` but there is one called `en-US`

Any advice please?

**Comment by Steve-Mcl** [comment]
So for anyone else reading this - this is how I got it running.

NOTE: This is what I did & not necessarily the right way.

## steps...
1. Install webpack and webpack-cli
   1. `npm install webpack -g`
   1. `npm install webpack-cli -g`
1. delete file `locales\en`
1. duplicate `en-US` directory and rename to `en`
1. run `webpack --bail --colors --display-error-details --config tools/webpack.config.js`
1. set env vars 
  ``` 
   set PASSWORD_SEED=fruk
   set PORT=3003
   set MONGO_URI=mongodb://crowi:**pass**@localhost:27000/crowi
   set NODE_ENV=development
   ```
1. `npm start`

And now it runs. :clap: :clap: :clap: 


## issues...
* font awesome icons not showing
![image](https://user-images.githubusercontent.com/44235289/66121440-226eeb00-e5d5-11e9-8cfa-2e8ab769e5b6.png)

* Settings UI is almost all Japanese...
   ![image](https://user-images.githubusercontent.com/44235289/66121510-48948b00-e5d5-11e9-8135-20d4553ea565.png)
   ![image](https://user-images.githubusercontent.com/44235289/66121534-5813d400-e5d5-11e9-885e-087bef69aa28.png)
   ![image](https://user-images.githubusercontent.com/44235289/66121491-403c5000-e5d5-11e9-8c40-fe65deb25f7d.png)

** I suspect I have missed something or done something wrong **

Please help.

Thanks.

**Comment by sotarok** [comment]
Hmm, it might be a `path` related issue.
Sorry I don't have Windows environment and I haven't care of it, but It could be fixed by edit webpack or somewhere around the build path I think ...

(And also sorry about missing translation for Admin screens. It could be a `good first issue` so could you please send a PR if you wanna try it 🙇  )

**Comment by sotarok** [comment]
> Looking in ../locales there is no directory called en/ but there is one called en-US/ and it does have a file named translation.yml

Ah ... it caused because `locales/en` is a symbolic link to `en-US` and symbolic link couldn't work on Windows system right?

**Comment by Steve-Mcl** [comment]
Symbol links are possible on windows but not normal. 

Couldn't this simply be a setting that points to the path instead?
