### ISSUE TITLE
elasticsearch not hit result

### ISSUE THREAD

**Issue by yuzu441** [crowi/crowi#613]
Hello Crowi team.

I tried Crowi master and a release(v1.7.9), but I couldn't get the search result.
(In v1.7.6, I was able to retrieve it.)

## steps to reproduce

1: clone repository
2: docker-compose -f docker-compose.development.yml up
3: create account and page contents
4: push "Build Now" button at "検索管理" on the admin page
5: move top page
6: type search keyword at search bar
7: No results for "keyword"

Can you teach some tips to solve this?

**Comment by lightnet328** [comment]
Hmm, I'd like to know more detail information to reproduce this issue.
Do you have any logs (either Crowi or Elasticsearch)?

**Comment by yuzu441** [comment]
Is the log that appears when I press the Build Now button useful for resolution?

> crowi_1          | [0] 2019-10-15T07:59:15.258Z crowi:crowi Websocket CONNECTED, socket.id: Sh-rl36We3boFBPHAAAG
crowi_1          | [0] 2019-10-15T07:59:16.272Z crowi:lib:search Index created.
crowi_1          | [0] 2019-10-15T07:59:16.287Z crowi:lib:search Sending last body of bulk operation: 4
crowi_1          | [0] 2019-10-15T07:59:16.290Z crowi:lib:search Added all pages.
crowi_1          | [0] 2019-10-15T07:59:16.404Z crowi:lib:search addAllPages add anyway (items, errors, took):  2 false 105 ms
crowi_1          | [0] 2019-10-15T07:59:16.437Z crowi:routes:admin Error caught. { Error: [invalid_alias_name_exception] Invalid alias name [crowi-current], an index exists with the same name as the alias, with { index_uuid="KJWe6-4RS_6cAxZlg5TCvA" & index="crowi-current" }
crowi_1          | [0]     at respond (/crowi/node_modules/elasticsearch/src/lib/transport.js:308:15)
crowi_1          | [0]     at checkRespForFailure (/crowi/node_modules/elasticsearch/src/lib/transport.js:267:7)
crowi_1          | [0]     at HttpConnector.<anonymous> (/crowi/node_modules/elasticsearch/src/lib/connectors/http.js:165:7)
crowi_1          | [0]     at IncomingMessage.wrapper (/crowi/node_modules/elasticsearch/node_modules/lodash/lodash.js:4949:19)
crowi_1          | [0]     at emitNone (events.js:111:20)
crowi_1          | [0]     at IncomingMessage.emit (events.js:208:7)
crowi_1          | [0]     at endReadableNT (_stream_readable.js:1064:12)
crowi_1          | [0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
crowi_1          | [0]     at process._tickCallback (internal/process/next_tick.js:180:9)
crowi_1          | [0]   status: 400,
crowi_1          | [0]   displayName: 'BadRequest',
crowi_1          | [0]   message: '[invalid_alias_name_exception] Invalid alias name [crowi-current], an index exists with the same name as the alias, with { index_uuid="KJWe6-4RS_6cAxZlg5TCvA" & index="crowi-current" }',
crowi_1          | [0]   path: '/_aliases',
crowi_1          | [0]   query: {},
crowi_1          | [0]   body:
crowi_1          | [0]    { error:
crowi_1          | [0]       { root_cause: [Array],
crowi_1          | [0]         type: 'invalid_alias_name_exception',
crowi_1          | [0]         reason: 'Invalid alias name [crowi-current], an index exists with the same name as the alias',
crowi_1          | [0]         index_uuid: 'KJWe6-4RS_6cAxZlg5TCvA',
crowi_1          | [0]         index: 'crowi-current' },
crowi_1          | [0]      status: 400 },
crowi_1          | [0]   statusCode: 400,
crowi_1          | [0]   response: '{"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [crowi-current], an index exists with the same name as the alias","index_uuid":"KJWe6-4RS_6cAxZlg5TCvA","index":"crowi-current"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [crowi-current], an index exists with the same name as the alias","index_uuid":"KJWe6-4RS_6cAxZlg5TCvA","index":"crowi-current"},"status":400}',
crowi_1          | [0]   toString: [Function],
crowi_1          | [0]   toJSON: [Function] }

**Comment by lightnet328** [comment]
Thanks! It was useful. I understand what happened. However, it still does not reproduce in my environment.
Which version of Elasticsearch are you using?? Elasticsearch v6.x.x may be required.

FYI:
The version of Elasticsearch in my environment is 6.3.2.

**Comment by lightnet328** [comment]
If you are using docker-compose, Elasticsearch version will be v6.3.2 ...?

**Comment by yuzu441** [comment]
Yes I using docker-compose and es v6.3.2.

**Comment by lightnet328** [comment]
Hmm, after all, I can't reproduce it, so I can't treat it as a bug. I'm sorry, I'll keep it in my memory.

Anyway, I think you can delete Elasticsearch data once to solve this problem. Could you try it?

**Comment by yuzu441** [comment]
I try `rm -rf data/`but I can't hit result...
if not a bug I close this issue. please let me know when you understand anything.

Thank you for help. 🙏

**Comment by lightnet328** [comment]
@yuzu441 Just question, did you rebuild index after that?

P.S.
I mean I think it maybe a bug but I can't fix it now🙏

**Comment by yuzu441** [comment]
@lightnet328 Yes, I did rebuild index.

**Comment by lightnet328** [comment]
Hmm...🤔

Behaviors in my environment:

1. `docker-compose -f docker-compose.development.yml stop`
2. `rm -rf data/elasticsearch`
3. `docker-compose -f docker-compose.development.yml start`
4. Open `localhost:3000`
5. Search ... e.g. `test`

Crowi outpus:

```
crowi:lib:search Search error { Error: [index_not_found_exception] no such index, with { resource.type="index_or_alias" & resource.id="crowi-current" & index_uuid="_na_" & index="crowi-current" }
```

6. Rebuild index

Crowi outputs:

```
[0] 2019-10-23T11:55:29.430Z crowi:lib:search Index created.
[0] 2019-10-23T11:55:29.476Z crowi:lib:search Sending last body of bulk operation: 4
[0] 2019-10-23T11:55:29.485Z crowi:lib:search Added all pages.
[0] 2019-10-23T11:55:29.682Z crowi:routes:admin Data is successfully indexed. ------------------ ✧✧
[0] 2019-10-23T11:55:29.712Z crowi:lib:search addAllPages add anyway (items, errors, took):  2 false 202 ms
```

How about you? (Sorry for continuing...)

**Comment by yuzu441** [comment]
@lightnet328 I got the result in the way you told me.

Thanks a million!!😭
