### ISSUE TITLE
heroku新規deployで検索ができない（Elasticsearch v7対応）

### ISSUE THREAD

**Issue by tomoshin** [crowi/crowi#640]
いつもありがとうございます。
heroku freeプランの標準ではElasticsearchバージョンの指定ができないため、v7系がインストールされる。これが原因で検索をbuildしてもエラーとなるのではないかと思われます。
優先度は低いかもしれませんが、ご確認よろしくお願いします。

**Comment by lightnet328** [comment]
ご利用ありがとうございます。
v1.8.0 で Elasticsearch v7 への対応を予定しています。
まだ、マージはされていませんが PR はこちらです。
https://github.com/crowi/crowi/pull/622
v1.8.0 のリリースに向けて、この PR の他にもいくつか残作業がありますので、リリースにはもうしばらく時間がかかります。

---

We have a plan to support Elasticsearch v7 in v1.8.0.
This is a PR for supporting Elasticsearch v7, but it's not merged yet.
https://github.com/crowi/crowi/pull/622
There are other remaining tasks for the v1.8.0 release, so the release will take a while.

**Comment by tomoshin** [comment]
ご回答ありがとうございます！
PRに気付いておらず、申し訳ありませんでした。issue closeします。
