### ISSUE TITLE
Can not remove user

### ISSUE THREAD

**Issue by fideltak** [crowi/crowi#654]
Hello team
### Scenario
I tried to delete a user via admin web page, but got an error.
The target user is not admin.
```
2020-03-01T13:43:30.559Z crowi:middlewares:csrfVerify req.skipCsrfVerify undefined
2020-03-01T13:43:30.561Z crowi:models:user Activate User { lang: 'en-US',
  status: 3,
  admin: true,
  _id: 5e5bb88f7e525b00120d5117,
  createdAt: 2020-03-01T13:28:47.650Z,
  email: '<user email>',
  __v: 0,
  name: '<user name>',
  username: '<username>' }
POST /_api/admin/user/5e5bb5277e525b00120d50fa/remove 404 0.378 ms - 187
POST /_api/admin/user/5e5bb5277e525b00120d50fa/remove 404 0.381 ms - 187
POST /_api/admin/user/5e5bb88f7e525b00120d5117/remove 404 0.405 ms - 187
```
### Environment Details
Crowi Version: 1.8.0-dev
Im using crowi docker container image and deploy it on k8s v1.17.3.

### Steps to Reproduce
Make users and delete them by using crowi container image.

**Comment by sotarok** [comment]
Thank you Thank you for using Crowi, and sorry for inconvenient.
The user deletion feature is not yet implemented.
Please use "suspend" flag instead until we deliver this feature to users 🙇

**Comment by fideltak** [comment]
@sotarok 
OK, I will do user operation by using it.
