### ISSUE TITLE
[Feature Request] Only listen on localhost interface

### ISSUE THREAD

**Issue by ishigoya** [crowi/crowi#741]
Would it be possible to add an option to only listen on the localhost interface? I am running crowi on a Linux server, and intend to put the application behind an Nginx proxy. I would prefer not to have the server listening on other interfaces if possible.

I'm not very good with Javascript, but would be happy to submit a pull request to implement this.

**Comment by sotarok** [comment]
Thank you for the feedback.

Yes, I can understand your request to restrict the listening interface for some security reason.

But, actually, there are variety of infrastructure environments Crowi running.
For example, I run Crowi on ECS AWS and work with LB, Nginx container and Crowi container. In this case, Crowi doesn't listen localhost but the network interface that connect to the front Nginx container.

So, IMHO, Crowi doesn't have to care the environment whether should only listen localhost or not.
Instead, you can restrict the network interfaces in several ways: use iptables when you use Linux server, use Security Group settings or some other network settings when you use AWS and so far.

**Comment by ishigoya** [comment]
> Instead, you can restrict the network interfaces in several ways: use iptables when you use Linux server, use Security Group settings or some other network settings when you use AWS and so far.

The ability to set which network interfaces a utility binds to is a standard feature. I can't remember the last time I had to use iptables or a similar mechanism to prevent access to software listening on a network interface. In my opinion, it would be very unusual not to have this ability.

> So, IMHO, Crowi doesn't have to care the environment whether should only listen localhost or not.

It doesn't have to care, as long as users installing to a server implement the workaround you mentioned above. If that's the case, I think it would be really helpful to reflect this in the install documentation, because I think it will be a surprise to users installing to servers.
