### ISSUE TITLE
password length validation rules are different between some forms

### ISSUE THREAD

**Issue by supermomonga** [crowi/crowi#77]
## Problem

We can set 41 or more chars to the password when register, but login form limits max length to 40 chars.
## Solution(Suggestion)
- option1) Implement validates to the register form to ensure that password is less than 40 chars.
- option2) Remove max length limit validation for password

I think option2 is better, unless we can explain why we should limit password length, or why the 40 chars is the best length of the limit.

**Comment by sotarok** [comment]
Thank you for the feedback.
I'll fix it.

**Comment by sotarok** [comment]
fixed in #90.
