### ISSUE TITLE
Top page is didn't work if editing same file at the same time.

### ISSUE THREAD

**Issue by rinov** [crowi/crowi#81]
We edited table of contents at the some time by some people.
it'll occur error.
After that editing function will be suspended. 
In addition this situation has been continued even if Crowi is restart.

Centos7
$ nvm --version
0.26.1
$ npm -v
3.8.9
$ node -v
v6.2.0
$ ruby -v
v2.3.1

**Comment by sotarok** [comment]
Thank you for the feedback.
I'll check the condition of this case and try to reproduce it.

**Comment by sotarok** [comment]
Finally I couldn't reproduce this issue.
If you still have the same problem, please report again with the reproducing process.
