### ISSUE TITLE
wish list

### ISSUE THREAD

**Issue by tknr** [crowi/crowi#93]
If possible I hope to implement the following functions .

- import json or md file ( from qiita )
- tag on memo
- search memo with text

**Comment by sotarok** [comment]
Thank you for the comment! :)

## Importer

Importer will be implemented.

## Tag

IMHO, tag is not work for organising information. I've seen a lot of case that tags are not maintained.
So there is no plan to implement "tag" feature.

## Search memo with text

Search feature is now being implemented.

**Comment by sotarok** [comment]
Close this issue because I answered these comments.
Really thank you for the feedback.
